import React, { useState, useEffect, useCallback } from "react";
import { fetchAllClaims, fetchAnalytics } from "../api/adminApi.js";
import RiskBadge from "../components/RiskBadge.jsx";

export default function AdminDashboard() {
  const [claims, setClaims] = useState([]);
  const [analytics, setAnalytics] = useState(null);
  const [filter, setFilter] = useState("ALL");
  const [loading, setLoading] = useState(true);

  const load = useCallback(async () => {
    try {
      const [claimsData, analyticsData] = await Promise.all([fetchAllClaims(), fetchAnalytics()]);
      setClaims(claimsData.claims || []);
      setAnalytics(analyticsData);
    } catch { } finally { setLoading(false); }
  }, []);

  useEffect(() => { load(); const id = setInterval(load, 15000); return () => clearInterval(id); }, [load]);

  const filtered = filter === "ALL" ? claims :
    filter === "AUTO" ? claims.filter(c => c.autoGenerated) :
      claims.filter(c => c.riskResult?.claimStatus === filter);

  const s = analytics?.summary || {};

  return (
    <div className="min-h-screen pt-20 px-4 md:px-10 pb-12">
      <div className="mb-6">
        <p className="font-mono text-[10px] text-white/30 uppercase tracking-widest mb-1">Admin / Insurer View</p>
        <h1 className="display-text text-4xl md:text-5xl text-white">COMMAND CENTER</h1>
      </div>

      {/* KPI Row */}
      <div className="grid grid-cols-2 md:grid-cols-6 gap-3 mb-6">
        {[
          { label: "Total Claims", value: s.totalClaims || 0, accent: "text-white" },
          { label: "Auto-Generated", value: s.autoGeneratedClaims || 0, accent: "text-electric-blue" },
          { label: "Workers", value: s.totalWorkers || 0, accent: "text-white" },
          { label: "Active Policies", value: s.activePolicies || 0, accent: "text-signal-green" },
          { label: "Active Triggers", value: s.activeTriggers || 0, accent: s.activeTriggers > 0 ? "text-signal-red" : "text-white/40" },
          { label: "Loss Ratio", value: `${s.lossRatio || 0}%`, accent: (s.lossRatio || 0) > 80 ? "text-signal-red" : "text-signal-green" },
        ].map(kpi => (
          <div key={kpi.label} className="glass-card rounded-sm p-3 text-center">
            <p className="font-mono text-[9px] text-white/30 uppercase tracking-widest mb-1">{kpi.label}</p>
            <p className={`display-text text-xl ${kpi.accent}`}>{kpi.value}</p>
          </div>
        ))}
      </div>

      {/* Financial KPIs */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-3 mb-6">
        <div className="glass-card rounded-sm p-4 text-center border border-signal-green/10">
          <p className="font-mono text-[9px] text-white/30 uppercase mb-1">Premiums Collected</p>
          <p className="display-text text-2xl text-signal-green">₹{(s.totalPremiumsCollected || 0).toLocaleString()}</p>
        </div>
        <div className="glass-card rounded-sm p-4 text-center border border-signal-yellow/10">
          <p className="font-mono text-[9px] text-white/30 uppercase mb-1">Total Disbursed</p>
          <p className="display-text text-2xl text-signal-yellow">₹{(s.totalPayoutsDisbursed || 0).toLocaleString()}</p>
        </div>
        <div className="glass-card rounded-sm p-4 text-center border border-signal-red/10">
          <p className="font-mono text-[9px] text-white/30 uppercase mb-1">Liquidity At Risk</p>
          <p className="display-text text-2xl text-signal-red">₹{(s.liquidityRiskINR || 0).toLocaleString()}</p>
        </div>
        <div className="glass-card rounded-sm p-4 text-center border border-electric-blue/10">
          <p className="font-mono text-[9px] text-white/30 uppercase mb-1">Fraud Savings</p>
          <p className="display-text text-2xl text-electric-blue">₹{(s.savedLiquidityINR || 0).toLocaleString()}</p>
        </div>
      </div>

      {/* Active Triggers Alert */}
      {analytics?.activeTriggers?.length > 0 && (
        <div className="mb-6 border border-signal-red/30 bg-signal-red/5 rounded-sm p-4 animate-blink-border">
          <div className="flex items-center gap-2 mb-2">
            <span className="w-2 h-2 rounded-full bg-signal-red animate-pulse" />
            <span className="font-mono text-[10px] text-signal-red uppercase tracking-widest">Active Parametric Triggers</span>
          </div>
          <div className="space-y-1">
            {analytics.activeTriggers.map(t => (
              <div key={t.id} className="flex items-center justify-between">
                <span className="font-mono text-[10px] text-white/70">{t.label} — {t.zoneId.replace(/_/g, " ")}</span>
                <span className="font-mono text-[9px] text-white/30">{t.affectedWorkers} workers • {t.autoClaimIds?.length} claims</span>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Filter Tabs */}
      <div className="flex items-center gap-2 mb-4">
        {["ALL", "APPROVED", "MANUAL_REVIEW", "FLAGGED", "AUTO"].map(f => (
          <button key={f} onClick={() => setFilter(f)}
            className={`font-mono text-[10px] uppercase tracking-wider px-3 py-1.5 rounded-sm border transition-all ${filter === f ? "bg-white/10 border-white/20 text-white" : "border-white/6 text-white/30 hover:text-white/60"
              }`}>{f === "MANUAL_REVIEW" ? "REVIEW" : f} ({
              f === "ALL" ? claims.length :
                f === "AUTO" ? claims.filter(c => c.autoGenerated).length :
                  claims.filter(c => c.riskResult?.claimStatus === f).length
            })</button>
        ))}
      </div>

      {/* Claims Feed */}
      <div className="glass-card rounded-sm">
        <div className="px-6 py-4 border-b border-white/6">
          <span className="font-mono text-[10px] text-white/35 uppercase tracking-widest">Claims Feed — {filtered.length} claims</span>
        </div>
        <div className="divide-y divide-white/5">
          {filtered.slice(0, 30).map(claim => (
            <div key={claim.id} className="px-6 py-4 hover:bg-white/[0.02] transition-colors">
              <div className="flex items-center justify-between mb-2">
                <div className="flex items-center gap-3">
                  <RiskBadge score={claim.riskResult?.riskScore} status={claim.riskResult?.claimStatus} />
                  <div>
                    <span className="font-mono text-sm text-white/80">{claim.workerName}</span>
                    <span className="font-mono text-[9px] text-white/25 ml-2">{claim.workerId}</span>
                    {claim.autoGenerated && (
                      <span className="ml-2 font-mono text-[8px] text-electric-blue bg-electric-blue/10 border border-electric-blue/20 px-1.5 py-0.5 rounded-sm">AUTO</span>
                    )}
                  </div>
                </div>
                <span className="font-mono text-[9px] text-white/20">{new Date(claim.submittedAt).toLocaleString()}</span>
              </div>
              <div className="flex items-center gap-3 ml-16">
                <span className="font-mono text-[9px] text-white/30">{claim.incident?.incidentType?.replace(/_/g, " ")}</span>
                <span className="font-mono text-[9px] text-white/15">•</span>
                <span className="font-mono text-[9px] text-white/25">{claim.incident?.zoneId?.replace(/_/g, " ")}</span>
              </div>
              {claim.riskResult?.fraudSignals?.length > 0 && (
                <div className="flex flex-wrap gap-1 mt-2 ml-16">
                  {claim.riskResult.fraudSignals.map(s => (
                    <span key={s} className="font-mono text-[8px] uppercase px-1.5 py-0.5 bg-signal-red/10 text-signal-red/70 border border-signal-red/15 rounded-sm">{s.replace(/_/g, " ")}</span>
                  ))}
                </div>
              )}
            </div>
          ))}
          {filtered.length === 0 && (
            <div className="px-6 py-10 text-center">
              <p className="font-mono text-[10px] text-white/20">No claims match this filter</p>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}