// server/src/controllers/adminController.js

import {
  getAllClaims,
  getFlaggedClaims,
  getRecentClaims,
} from "../data/claimsStore.js";
import { buildClusterGroups } from "../services/riskEngine/peerClusterDetector.js";
import { getAllZones } from "../data/weatherHistory.js";
import { CLAIM_STATUS } from "../../../shared/constants/riskThresholds.js";
import { getAllWorkers } from "../data/workersStore.js";
import { getAllPolicies } from "../data/policiesStore.js";
import { getAllPayouts, getTotalPayoutsINR } from "../data/payoutsStore.js";
import { getAllTriggerEvents, getActiveTriggers } from "../data/triggerEventsStore.js";
import { fetchAllZonesWeather, fetchAllZonesAQI } from "../services/weatherService.js";

/**
 * GET /api/admin/claims
 */
export const listAllClaims = async (req, res) => {
  try {
    const claims = getAllClaims();
    return res.json({
      total: claims.length,
      flagged: claims.filter((c) => c.riskResult?.claimStatus === CLAIM_STATUS.FLAGGED).length,
      approved: claims.filter((c) => c.riskResult?.claimStatus === CLAIM_STATUS.APPROVED).length,
      manual: claims.filter((c) => c.riskResult?.claimStatus === CLAIM_STATUS.MANUAL_REVIEW).length,
      autoGenerated: claims.filter((c) => c.autoGenerated).length,
      claims,
    });
  } catch (err) {
    return res.status(500).json({ error: "Internal server error" });
  }
};

/**
 * GET /api/admin/clusters
 */
export const getClusters = async (req, res) => {
  try {
    const recentClaims = getRecentClaims(120);
    const clusters = buildClusterGroups(recentClaims);

    return res.json({
      clusterCount: clusters.length,
      totalClusteredClaims: clusters.reduce((s, c) => s + c.claimCount, 0),
      clusters,
    });
  } catch (err) {
    return res.status(500).json({ error: "Internal server error" });
  }
};

/**
 * GET /api/admin/analytics
 */
export const getAnalytics = async (req, res) => {
  try {
    const allClaims = getAllClaims();
    const recentClaims = getRecentClaims(60);
    const clusters = buildClusterGroups(getRecentClaims(120));
    const weatherZones = getAllZones();
    const workers = getAllWorkers();
    const policies = getAllPolicies();
    const payouts = getAllPayouts();
    const triggers = getAllTriggerEvents();
    const activeTriggers = getActiveTriggers();

    // Signal frequency breakdown
    const signalFrequency = {};
    allClaims.forEach((c) => {
      (c.riskResult?.fraudSignals || []).forEach((sig) => {
        signalFrequency[sig] = (signalFrequency[sig] || 0) + 1;
      });
    });

    // Risk score distribution buckets
    const distribution = { low: 0, medium: 0, high: 0, critical: 0 };
    allClaims.forEach((c) => {
      const s = c.riskResult?.riskScore || 0;
      if (s < 30) distribution.low++;
      else if (s < 60) distribution.medium++;
      else if (s < 80) distribution.high++;
      else distribution.critical++;
    });

    // Financial metrics
    const totalPremiumsCollected = policies.reduce((s, p) => s + p.premiumINR, 0);
    const totalPayoutsDisbursed = getTotalPayoutsINR();
    const lossRatio = totalPremiumsCollected > 0
      ? Math.round((totalPayoutsDisbursed / totalPremiumsCollected) * 100)
      : 0;

    const MOCK_PAYOUT = 5000;
    const riskyCount = allClaims.filter(
      (c) =>
        c.riskResult?.claimStatus === CLAIM_STATUS.FLAGGED ||
        c.riskResult?.claimStatus === CLAIM_STATUS.MANUAL_REVIEW
    ).length;
    const liquidityRiskINR = riskyCount * MOCK_PAYOUT;
    const savedLiquidityINR =
      allClaims.filter((c) => c.riskResult?.claimStatus === CLAIM_STATUS.FLAGGED).length * MOCK_PAYOUT;

    const avgRiskScore = allClaims.length
      ? Math.round(allClaims.reduce((s, c) => s + (c.riskResult?.riskScore || 0), 0) / allClaims.length)
      : 0;

    // Worker risk tier distribution
    const riskTierDistribution = { LOW: 0, MEDIUM: 0, HIGH: 0 };
    workers.forEach((w) => {
      const tier = w.riskProfile?.riskTier || "MEDIUM";
      riskTierDistribution[tier] = (riskTierDistribution[tier] || 0) + 1;
    });

    // Fetch live weather for zones
    let liveWeather = [];
    try {
      liveWeather = await fetchAllZonesWeather();
    } catch { /* use static fallback */ }

    let liveAQI = [];
    try {
      liveAQI = await fetchAllZonesAQI();
    } catch { /* use static fallback */ }

    return res.json({
      summary: {
        totalClaims: allClaims.length,
        recentClaims: recentClaims.length,
        flaggedClaims: distribution.critical + distribution.high,
        clusterCount: clusters.length,
        avgRiskScore,
        liquidityRiskINR,
        savedLiquidityINR,
        // New metrics
        totalWorkers: workers.length,
        activePolicies: policies.filter((p) => p.status === "ACTIVE").length,
        totalPremiumsCollected,
        totalPayoutsDisbursed,
        lossRatio,
        activeTriggers: activeTriggers.length,
        autoGeneratedClaims: allClaims.filter((c) => c.autoGenerated).length,
      },
      signalFrequency,
      riskDistribution: distribution,
      riskTierDistribution,
      clusters,
      weatherZones,
      liveWeather,
      liveAQI,
      triggers: triggers.slice(0, 20),
      activeTriggers,
      topRiskClaims: allClaims
        .sort((a, b) => (b.riskResult?.riskScore || 0) - (a.riskResult?.riskScore || 0))
        .slice(0, 5)
        .map((c) => ({
          id: c.id,
          workerName: c.workerName,
          riskScore: c.riskResult?.riskScore,
          claimStatus: c.riskResult?.claimStatus,
          fraudSignals: c.riskResult?.fraudSignals,
          autoGenerated: c.autoGenerated || false,
        })),
      policyMetrics: {
        total: policies.length,
        active: policies.filter((p) => p.status === "ACTIVE").length,
        avgPremium: policies.length
          ? Math.round(policies.reduce((s, p) => s + p.premiumINR, 0) / policies.length)
          : 0,
      },
      payoutMetrics: {
        total: payouts.length,
        completed: payouts.filter((p) => p.status === "COMPLETED").length,
        pending: payouts.filter((p) => p.status === "PENDING").length,
        totalDisbursed: totalPayoutsDisbursed,
      },
    });
  } catch (err) {
    console.error("getAnalytics error:", err);
    return res.status(500).json({ error: "Internal server error" });
  }
};